Step 3 - Added game core classes Asker and Console with specs
valter0ff/codebreaker_console pull request #2
Opened 2022-01-24 16:06 UTC by valter0ff

2022-01-28 13:49 UTC, etherell requested changes

2022-01-28 13:49 UTC, etherell commented on spec/lib/asker_spec.rb
> +        # expect(stats).to receive(:show_statistics)
Should it be deleted?

2022-01-28 13:49 UTC, etherell commented on spec/lib/asker_spec.rb
> +        # let(:stats) { double }
Please check the comments. Are they needed?

2022-01-28 13:49 UTC, etherell commented on lib/console.rb
> +  PLUSES = '++++'.freeze
I suggest renaming to WIN_RESULT or something like this. It will be clearer

2022-01-28 13:49 UTC, etherell commented on lib/console.rb
> +  # include DatabaseLoader
I suggest avoiding adding any comments to the code

2022-01-28 13:49 UTC, etherell commented on lib/console.rb
> +    end
I suggest trying to use guard clauses here, like this:

```ruby
return user_win if check == PLUSES
return user_lose(check) if game.no_more_attempts?

out_message I18n.t('messages.result_of_guess', result: check)
```

It will be a little shorter and easier to read

2022-01-28 13:49 UTC, etherell commented on spec/lib/console_spec.rb
> +        allow(console.game).to receive(:give_hint).and_return(is_hint)
better to move to before

2022-01-28 13:49 UTC, etherell commented on spec/lib/console_spec.rb
> +        is_hint = double
I can't understand what means double here?
Also I suggest moving is_hint to let

2022-01-28 13:49 UTC, etherell commented on spec/lib/console_spec.rb
> +        allow(console.game).to receive(:hint_present?).and_return(false)
better move to before

2022-01-28 13:49 UTC, etherell commented on spec/lib/console_spec.rb
> +    #     end
Please, add this in the next PR. And remove from this one

2022-01-28 14:05 UTC, valter0ff commented on lib/console.rb
> +  # include DatabaseLoader
Done!

2022-01-28 14:07 UTC, valter0ff commented on lib/console.rb
> +  PLUSES = '++++'.freeze
Done!

2022-01-28 14:09 UTC, valter0ff commented on lib/console.rb
> +    end
Good idea! Done!

2022-01-28 14:29 UTC, valter0ff commented on spec/lib/console_spec.rb
> +        allow(console.game).to receive(:give_hint).and_return(is_hint)
Done!

2022-01-28 14:30 UTC, valter0ff commented on spec/lib/console_spec.rb
> +        is_hint = double
Move to `let` done! 
This test example checks the behavior of `take_hint` method, so isn't matter what will return `console.game.give_hint`.

2022-01-28 14:30 UTC, valter0ff commented on spec/lib/console_spec.rb
> +        allow(console.game).to receive(:hint_present?).and_return(false)
Done!

2022-01-28 14:34 UTC, valter0ff commented on spec/lib/asker_spec.rb
> +        # expect(stats).to receive(:show_statistics)
Yes.

2022-01-28 14:34 UTC, valter0ff commented on spec/lib/asker_spec.rb
> +        # let(:stats) { double }
Removed

2022-02-01 12:30 UTC, etherell approved these changes

2022-02-01 12:30 UTC, etherell commented on lib/console.rb
> +    out_message I18n.t('messages.result_of_guess', result: check)
Please add bracers here

2022-02-01 12:30 UTC, etherell commented on lib/console.rb
> +    out_message I18n.t('messages.secret_code', code: game.secret_code.join)
Please add bracers here too

2022-02-01 22:00 UTC, valter0ff commented on lib/console.rb
> +    out_message I18n.t('messages.result_of_guess', result: check)
Done!

2022-02-01 22:00 UTC, valter0ff commented on lib/console.rb
> +    out_message I18n.t('messages.secret_code', code: game.secret_code.join)
Done!

2022-02-01 22:00 UTC, merged