Step 2 - Added Router class with specs
valter0ff/codebreaker_console pull request #4
Opened 2022-01-24 18:39 UTC by valter0ff

2022-01-28 13:21 UTC, etherell requested changes

2022-01-28 13:21 UTC, etherell commented on lib/router.rb
> +class Router
I think this PR should not be second because you're using asker here, but it will be added in the next PR

2022-01-28 15:56 UTC, valter0ff commented on lib/router.rb
> +class Router
I suggest no to change PR's order because `asker` not used with requested behavior, but just like Not Implemented yet entity.

2022-02-01 12:25 UTC, etherell approved these changes

2022-02-01 21:53 UTC, merged